name: Compile executable with ahk2exe

on: push

jobs:
  ahk2exe:
    name: ahk2exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: pacs-assistant.ahk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pacs-assistant.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
